---
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384

###############################################################################################

http:
  middlewares:
    compression:
      compress:
        excludedContentTypes:
          - text/event-stream

    security:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        sslRedirect: true
        sslForceHost: true
        stsPreload: true
        customFrameOptionsValue: SAMEORIGIN
        referrerPolicy: "same-origin"
        featurePolicy: "camera 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none'; vibrate 'self';"
        stsSeconds: 315360000
        hostsProxyHeaders:
          - "X-Forwarded-Host"

    authentification:
      basicAuth:
        users:
        - admin:$2y$10$byzmasKak2LLmvY86KcnGO0pX8UaaNDxQZMJW.wMmaoHRhjNXqOwG # admin/admin, use "https://bcrypt.fr" to encrypt your password

###############################################################################################

  routers:
    rt-traefik:
      entryPoints:
      - websecure
      middlewares:
      - authentification
      service: api@internal
      rule: Host (`dc.computerz.solutions`)
      tls:
        certResolver: letsencrypt

    rt-wordpress:
      entryPoints:
      - websecure
      middlewares:
      - security
      - compression
      service: sc-wordpress
      rule: Host (`computerz.solutions`)
      tls:
        certResolver: letsencrypt

    rt-portainer:
      entryPoints:
      - websecure
      middlewares:
      - security
      service: sc-portainer
      rule: Host(`portainer.computerz.solutions`)
      tls:
        certResolver: letsencrypt

#    rt-prometheus:
#      entryPoints:
#      - websecure
#      middlewares:
#      - authentification
#      service: sc-prometheus
#      rule: Host (`prom.computerz.solutions`)
#      tls:
#        certResolver: letsencrypt

    rt-grafana:
      entryPoints:
      - websecure
      middlewares:
      - security
      service: sc-grafana
      rule: Host (`graf.computerz.solutions`)
      tls:
        certResolver: letsencrypt

    rt-matomo:
      entryPoints:
      - websecure
      middlewares:
      - security
      service: sc-matomo
      rule: Host (`stats.computerz.solutions`)
      tls:
        options: default
        certResolver: letsencrypt

# ###########################

  services:
    sc-wordpress:
      loadBalancer:
        servers:
        - url: "http://nginxwp:80"

    sc-portainer:
      loadBalancer:
        servers:
        - url: "http://portainer:9000"

    sc-grafana:
      loadBalancer:
        servers:
        - url: "http://grafana:3000"

#    sc-prometheus:
#      loadBalancer:
#        servers:
#        - url: "http://prometheus:9090"

    sc-matomo:
      loadBalancer:
        servers:
        - url: "http://nginxmatomo:80"
